# This is a basic workflow to help you get started with Actions
name: CI Pipeline

on: 
  push:
      branches:
        - main

  workflow_dispatch:

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: 
          node-version: 20
      
      # changes to the reactCICD directory, installs dependencies, runs tests, and builds the project
      - run: npm install
        working-directory: ./reactCICD

      - run: npm test
        working-directory: ./reactCICD

      - run: npm run build
        working-directory: ./reactCICD



